### ISSUE TITLE
Networking toast

### ISSUE THREAD

**Issue by zeromentu** [684102/FacebookOnly#1]
When my phone gets unlocked I have a toast message that says networking enabled it was nice to doesn't
Thanks for the work

**Comment by 684102** [comment]
[v0.3](https://github.com/684102/FacebookOnly/releases/tag/v0.3) : Facebook app only send/receive data whenever device screen is turned ON.

**Comment by zeromentu** [comment]
Yes, that's a great feature, however the toast message can be hidden?

**Comment by 684102** [comment]
[v0.4](https://github.com/684102/FacebookOnly/releases/tag/v0.4) : Hide networking toast.
