### ISSUE TITLE
Constant notification

### ISSUE THREAD

**Issue by zeromentu** [684102/FacebookOnly#2]
Hoping not disturbing with the issues, since I'm trying to contribute for the project
After latest update and clearing data in always getting a notification from Facebook saying that I have a notification, no info at all. If I clear it, it shows after some seconds even while I'm browsing on feed.
![Screenshot_2020-07-14-22-03-49-205_com facebook katana](https://user-images.githubusercontent.com/46009510/87476429-478d9100-c61e-11ea-830e-b42c64746dde.jpg)

**Comment by 684102** [comment]
Hello, you can turn any notification off, just taphold on that , then select configuration (or settings on some device) . 
Now you can manage all of notification of selected app.

**Comment by zeromentu** [comment]
Since I still want to have some notifications I don't want to disable all of them, and all the notifications came with the same text: "new notification" not even translated, so I can't really see what's the notification
Maybe it's Facebook base build related

**Comment by 684102** [comment]
Yoy can select to disable one instead all notification of that app by my way dude.

**Comment by zeromentu** [comment]
Yeah, but notifications aren't showing the content
