### ISSUE TITLE
Ads everywhere

### ISSUE THREAD

**Issue by wennaspeedy** [684102/FacebookOnly#3]
I still see ads in facebook or messenger. I have fb as systemapp.

**Comment by 684102** [comment]
We have 3 type of people when use my apk mod.
some body doesn't have any ads
some body have some ads
and some body have ads anywhere

**Comment by wennaspeedy** [comment]
I have custom magisk-rooted android-q rom.  What kind of rom does this app work?

Here is ad-free facebook app that really works:
https://forum.xda-developers.com/android/apps-games/bullshified-version-facebook-okay-to-t3586318

Your doesnt, it seems it is not easy as adding hosts file.

**Comment by zeromentu** [comment]
That's was rude... i hope dev keep the good work and gets all the support
